<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.fabridinapoli.kotlinorms.componenttest.SignUpCustomerShould" tests="1" skipped="0" failures="0" errors="0" timestamp="2023-02-05T14:35:00" hostname="MacBook-Air.local" time="0.495">
  <properties/>
  <testcase name="sign up a customer successfully()" classname="com.fabridinapoli.kotlinorms.componenttest.SignUpCustomerShould" time="0.495"/>
  <system-out><![CDATA[15:33:47.731 [Test worker] DEBUG org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Neither @ContextConfiguration nor @ContextHierarchy found for test class [SignUpCustomerShould]: using SpringBootContextLoader
15:33:47.733 [Test worker] DEBUG org.springframework.test.context.support.AbstractContextLoader - Could not detect default resource locations for test class [com.fabridinapoli.kotlinorms.componenttest.SignUpCustomerShould]: no resource found for suffixes {-context.xml, Context.groovy}.
15:33:47.842 [Test worker] DEBUG org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Using ContextCustomizers for test class [SignUpCustomerShould]: [MockkContextCustomizer, DisableObservabilityContextCustomizer, PropertyMappingContextCustomizer, Customizer, ExcludeFilterContextCustomizer, DuplicateJsonObjectContextCustomizer, MockitoContextCustomizer, TestRestTemplateContextCustomizer, WebTestClientContextCustomizer, DynamicPropertiesContextCustomizer]
15:33:47.905 [Test worker] DEBUG org.springframework.test.context.util.TestContextSpringFactoriesUtils - Skipping candidate TestExecutionListener [org.springframework.test.context.web.ServletTestExecutionListener] due to a missing dependency. Specify custom TestExecutionListener classes or make the default TestExecutionListener classes and their required dependencies available. Offending class: [jakarta/servlet/ServletContext]
15:33:47.915 [Test worker] DEBUG org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Using TestExecutionListeners for test class [SignUpCustomerShould]: [DirtiesContextBeforeModesTestExecutionListener, ApplicationEventsTestExecutionListener, MockkTestExecutionListener, MockitoTestExecutionListener, DependencyInjectionTestExecutionListener, DirtiesContextTestExecutionListener, TransactionalTestExecutionListener, SqlScriptsTestExecutionListener, EventPublishingTestExecutionListener, ClearMocksTestExecutionListener, RestDocsTestExecutionListener, MockRestServiceServerResetTestExecutionListener, MockMvcPrintOnlyOnFailureTestExecutionListener, WebDriverTestExecutionListener, MockWebServiceServerTestExecutionListener, ResetMocksTestExecutionListener]
15:33:47.916 [Test worker] DEBUG org.springframework.test.context.support.AbstractDirtiesContextTestExecutionListener - Before test class: class [SignUpCustomerShould], class annotated with @DirtiesContext [false] with mode [null]
15:33:47.962 [Test worker] DEBUG org.springframework.test.context.support.DependencyInjectionTestExecutionListener - Performing dependency injection for test class com.fabridinapoli.kotlinorms.componenttest.SignUpCustomerShould
2023-02-05T15:33:48.118+01:00  INFO 49438 --- [    Test worker] o.t.utility.ImageNameSubstitutor         : Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
2023-02-05T15:33:48.128+01:00  INFO 49438 --- [    Test worker] o.t.d.DockerClientProviderStrategy       : Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
2023-02-05T15:33:48.331+01:00  INFO 49438 --- [    Test worker] o.t.d.DockerClientProviderStrategy       : Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
2023-02-05T15:33:48.333+01:00  INFO 49438 --- [    Test worker] org.testcontainers.DockerClientFactory   : Docker host IP address is localhost
2023-02-05T15:33:48.343+01:00  INFO 49438 --- [    Test worker] org.testcontainers.DockerClientFactory   : Connected to docker: 
  Server Version: 20.10.21
  API Version: 1.41
  Operating System: Docker Desktop
  Total Memory: 7951 MB
2023-02-05T15:33:48.368+01:00  INFO 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Pulling docker image: testcontainers/ryuk:0.3.4. Please be patient; this may take some time but only needs to be done once.
2023-02-05T15:33:49.419+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:33:49.422+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (118s remaining)
2023-02-05T15:33:50.143+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:33:50.144+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (118s remaining)
2023-02-05T15:33:50.868+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:33:50.869+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (117s remaining)
2023-02-05T15:33:51.594+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:33:51.595+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (116s remaining)
2023-02-05T15:33:52.305+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:33:52.306+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (116s remaining)
2023-02-05T15:33:53.045+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:33:53.046+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (115s remaining)
2023-02-05T15:33:53.723+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:33:53.725+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (114s remaining)
2023-02-05T15:33:54.424+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:33:54.427+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (113s remaining)
2023-02-05T15:33:55.129+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:33:55.130+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (113s remaining)
2023-02-05T15:33:55.850+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:33:55.851+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (112s remaining)
2023-02-05T15:33:56.581+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:33:56.581+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (111s remaining)
2023-02-05T15:33:57.273+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:33:57.274+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (111s remaining)
2023-02-05T15:33:57.945+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:33:57.947+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (110s remaining)
2023-02-05T15:33:58.641+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:33:58.642+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (109s remaining)
2023-02-05T15:33:59.309+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:33:59.310+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (109s remaining)
2023-02-05T15:33:59.981+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:33:59.982+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (108s remaining)
2023-02-05T15:34:00.732+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:00.733+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (107s remaining)
2023-02-05T15:34:01.452+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:01.453+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (106s remaining)
2023-02-05T15:34:02.171+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:02.172+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (106s remaining)
2023-02-05T15:34:02.861+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:02.863+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (105s remaining)
2023-02-05T15:34:03.605+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:03.605+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (104s remaining)
2023-02-05T15:34:04.318+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:04.319+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (104s remaining)
2023-02-05T15:34:05.025+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:05.027+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (103s remaining)
2023-02-05T15:34:05.835+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:05.837+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (102s remaining)
2023-02-05T15:34:06.541+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:06.542+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (101s remaining)
2023-02-05T15:34:07.267+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:07.269+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (101s remaining)
2023-02-05T15:34:08.038+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:08.039+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (100s remaining)
2023-02-05T15:34:08.821+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:08.823+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (99s remaining)
2023-02-05T15:34:09.567+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:09.568+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (98s remaining)
2023-02-05T15:34:10.304+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:10.305+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (98s remaining)
2023-02-05T15:34:11.078+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:11.079+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (97s remaining)
2023-02-05T15:34:11.801+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:11.802+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (96s remaining)
2023-02-05T15:34:12.522+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:12.522+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (95s remaining)
2023-02-05T15:34:13.244+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:13.245+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (95s remaining)
2023-02-05T15:34:13.945+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:13.947+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (94s remaining)
2023-02-05T15:34:14.734+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:14.735+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (93s remaining)
2023-02-05T15:34:15.489+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:15.489+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (92s remaining)
2023-02-05T15:34:16.209+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:16.210+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (92s remaining)
2023-02-05T15:34:16.932+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:16.933+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (91s remaining)
2023-02-05T15:34:17.677+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:17.678+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (90s remaining)
2023-02-05T15:34:18.389+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:18.391+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (89s remaining)
2023-02-05T15:34:19.174+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:19.174+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (89s remaining)
2023-02-05T15:34:19.935+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:19.936+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (88s remaining)
2023-02-05T15:34:20.696+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:20.698+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (87s remaining)
2023-02-05T15:34:21.472+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:21.475+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (86s remaining)
2023-02-05T15:34:22.257+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:22.258+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (86s remaining)
2023-02-05T15:34:22.997+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:22.998+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (85s remaining)
2023-02-05T15:34:23.749+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:23.750+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (84s remaining)
2023-02-05T15:34:24.519+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:24.520+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (83s remaining)
2023-02-05T15:34:25.312+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:25.313+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (83s remaining)
2023-02-05T15:34:26.020+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:26.022+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (82s remaining)
2023-02-05T15:34:26.781+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:26.782+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (81s remaining)
2023-02-05T15:34:27.491+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:27.492+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (80s remaining)
2023-02-05T15:34:28.195+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:28.196+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (80s remaining)
2023-02-05T15:34:28.890+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:28.892+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (79s remaining)
2023-02-05T15:34:29.654+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:29.656+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (78s remaining)
2023-02-05T15:34:30.443+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:30.444+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (77s remaining)
2023-02-05T15:34:31.213+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:31.214+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (77s remaining)
2023-02-05T15:34:31.973+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:31.974+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (76s remaining)
2023-02-05T15:34:32.703+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:32.704+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (75s remaining)
2023-02-05T15:34:33.505+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:33.506+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (74s remaining)
2023-02-05T15:34:34.257+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:34.258+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (74s remaining)
2023-02-05T15:34:35.019+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:35.020+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (73s remaining)
2023-02-05T15:34:36.027+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:36.028+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (72s remaining)
2023-02-05T15:34:36.763+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:36.764+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (71s remaining)
2023-02-05T15:34:37.467+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:37.468+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (70s remaining)
2023-02-05T15:34:38.195+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:38.196+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (70s remaining)
2023-02-05T15:34:38.925+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:38.927+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (69s remaining)
2023-02-05T15:34:39.667+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:39.671+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (68s remaining)
2023-02-05T15:34:40.409+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:40.410+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (67s remaining)
2023-02-05T15:34:41.123+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:41.126+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (67s remaining)
2023-02-05T15:34:41.857+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:41.858+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (66s remaining)
2023-02-05T15:34:42.627+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:42.628+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (65s remaining)
2023-02-05T15:34:43.381+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:43.382+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (64s remaining)
2023-02-05T15:34:44.099+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:44.100+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (64s remaining)
2023-02-05T15:34:44.828+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:44.829+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (63s remaining)
2023-02-05T15:34:45.555+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:45.556+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (62s remaining)
2023-02-05T15:34:46.315+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:46.316+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (62s remaining)
2023-02-05T15:34:47.054+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:47.055+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (61s remaining)
2023-02-05T15:34:47.800+01:00 ERROR 49438 --- [eam--1537471976] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.4\": toomanyrequests: too many failed login attempts for username or IP address"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.17.6.jar:1.17.6]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-02-05T15:34:47.801+01:00  WARN 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Retrying pull for image: testcontainers/ryuk:0.3.4 (60s remaining)
2023-02-05T15:34:49.342+01:00  INFO 49438 --- [eam--1537471976] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Starting to pull image
2023-02-05T15:34:49.362+01:00  INFO 49438 --- [eam--1537471976] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Pulling image layers:  0 pending,  0 downloaded,  0 extracted, (0 bytes/0 bytes)
2023-02-05T15:34:50.405+01:00  INFO 49438 --- [eam--1537471976] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Pulling image layers:  2 pending,  1 downloaded,  0 extracted, (1 MB/? MB)
2023-02-05T15:34:50.409+01:00  INFO 49438 --- [eam--1537471976] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Pulling image layers:  1 pending,  2 downloaded,  0 extracted, (1 MB/? MB)
2023-02-05T15:34:50.507+01:00  INFO 49438 --- [eam--1537471976] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Pulling image layers:  1 pending,  2 downloaded,  1 extracted, (3 MB/? MB)
2023-02-05T15:34:50.519+01:00  INFO 49438 --- [eam--1537471976] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Pulling image layers:  0 pending,  3 downloaded,  1 extracted, (3 MB/4 MB)
2023-02-05T15:34:50.555+01:00  INFO 49438 --- [eam--1537471976] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Pulling image layers:  0 pending,  3 downloaded,  2 extracted, (3 MB/4 MB)
2023-02-05T15:34:50.615+01:00  INFO 49438 --- [eam--1537471976] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Pulling image layers:  0 pending,  3 downloaded,  3 extracted, (4 MB/4 MB)
2023-02-05T15:34:50.620+01:00  INFO 49438 --- [eam--1537471976] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Pull complete. 3 layers, pulled in 1s (downloaded 4 MB at 4 MB/s)
2023-02-05T15:34:50.637+01:00  INFO 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Creating container for image: testcontainers/ryuk:0.3.4
2023-02-05T15:34:50.682+01:00  INFO 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Container testcontainers/ryuk:0.3.4 is starting: d75020ef442d184e7f871522ca8e8a1ae1376bf74b200cf66fb8daec72b0fce3
2023-02-05T15:34:50.897+01:00  INFO 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [testcontainers/ryuk:0.3.4]           : Container testcontainers/ryuk:0.3.4 started in PT1M2.550352S
2023-02-05T15:34:50.902+01:00  INFO 49438 --- [    Test worker] o.t.utility.RyukResourceReaper           : Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
2023-02-05T15:34:50.902+01:00  INFO 49438 --- [    Test worker] org.testcontainers.DockerClientFactory   : Checking the system...
2023-02-05T15:34:50.902+01:00  INFO 49438 --- [    Test worker] org.testcontainers.DockerClientFactory   : ✔︎ Docker server version should be at least 1.6.0
2023-02-05T15:34:50.905+01:00  INFO 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling docker image: postgres:15.1. Please be patient; this may take some time but only needs to be done once.
2023-02-05T15:34:52.501+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Starting to pull image
2023-02-05T15:34:52.503+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers:  0 pending,  0 downloaded,  0 extracted, (0 bytes/0 bytes)
2023-02-05T15:34:53.347+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers: 12 pending,  1 downloaded,  0 extracted, (45 KB/? MB)
2023-02-05T15:34:53.599+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers: 11 pending,  2 downloaded,  0 extracted, (7 MB/? MB)
2023-02-05T15:34:54.203+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers: 10 pending,  3 downloaded,  0 extracted, (28 MB/? MB)
2023-02-05T15:34:54.221+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers:  9 pending,  4 downloaded,  0 extracted, (28 MB/? MB)
2023-02-05T15:34:54.426+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers:  8 pending,  5 downloaded,  0 extracted, (36 MB/? MB)
2023-02-05T15:34:54.654+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers:  7 pending,  6 downloaded,  0 extracted, (36 MB/? MB)
2023-02-05T15:34:54.718+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers:  6 pending,  7 downloaded,  0 extracted, (36 MB/? MB)
2023-02-05T15:34:54.880+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers:  5 pending,  8 downloaded,  0 extracted, (40 MB/? MB)
2023-02-05T15:34:54.899+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers:  5 pending,  8 downloaded,  1 extracted, (40 MB/? MB)
2023-02-05T15:34:54.998+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers:  5 pending,  8 downloaded,  2 extracted, (41 MB/? MB)
2023-02-05T15:34:55.033+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers:  5 pending,  8 downloaded,  3 extracted, (41 MB/? MB)
2023-02-05T15:34:55.086+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers:  5 pending,  8 downloaded,  4 extracted, (41 MB/? MB)
2023-02-05T15:34:55.152+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers:  4 pending,  9 downloaded,  4 extracted, (41 MB/? MB)
2023-02-05T15:34:55.290+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers:  4 pending,  9 downloaded,  5 extracted, (46 MB/? MB)
2023-02-05T15:34:55.355+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers:  4 pending,  9 downloaded,  6 extracted, (47 MB/? MB)
2023-02-05T15:34:55.395+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers:  4 pending,  9 downloaded,  7 extracted, (47 MB/? MB)
2023-02-05T15:34:55.401+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers:  3 pending, 10 downloaded,  7 extracted, (52 MB/? MB)
2023-02-05T15:34:55.436+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers:  3 pending, 10 downloaded,  8 extracted, (52 MB/? MB)
2023-02-05T15:34:55.731+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers:  2 pending, 11 downloaded,  8 extracted, (66 MB/? MB)
2023-02-05T15:34:56.043+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers:  1 pending, 12 downloaded,  8 extracted, (77 MB/? MB)
2023-02-05T15:34:57.012+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers:  0 pending, 13 downloaded,  8 extracted, (126 MB/127 MB)
2023-02-05T15:34:58.350+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers:  0 pending, 13 downloaded,  9 extracted, (127 MB/127 MB)
2023-02-05T15:34:58.382+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers:  0 pending, 13 downloaded, 10 extracted, (127 MB/127 MB)
2023-02-05T15:34:58.413+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers:  0 pending, 13 downloaded, 11 extracted, (127 MB/127 MB)
2023-02-05T15:34:58.442+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers:  0 pending, 13 downloaded, 12 extracted, (127 MB/127 MB)
2023-02-05T15:34:58.478+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pulling image layers:  0 pending, 13 downloaded, 13 extracted, (127 MB/127 MB)
2023-02-05T15:34:58.483+01:00  INFO 49438 --- [ream--703880469] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Pull complete. 13 layers, pulled in 5s (downloaded 127 MB at 25 MB/s)
2023-02-05T15:34:58.486+01:00  INFO 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Creating container for image: postgres:15.1
2023-02-05T15:34:58.706+01:00  INFO 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Container postgres:15.1 is starting: 503131318bda46eab10be89052b69793e21ab55d2e47eabb4e139fe4c755190b
2023-02-05T15:34:59.551+01:00  INFO 49438 --- [    Test worker] ]]>&#x1f433;<![CDATA[ [postgres:15.1]                       : Container postgres:15.1 started in PT8.648814S
2023-02-05T15:34:59.560+01:00  INFO 49438 --- [    Test worker] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2023-02-05T15:34:59.668+01:00  INFO 49438 --- [    Test worker] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@274bae2c
2023-02-05T15:34:59.669+01:00  INFO 49438 --- [    Test worker] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2023-02-05T15:34:59.684+01:00  INFO 49438 --- [    Test worker] o.f.c.internal.license.VersionPrinter    : Flyway Community Edition 9.14.1 by Redgate
2023-02-05T15:34:59.684+01:00  INFO 49438 --- [    Test worker] o.f.c.internal.license.VersionPrinter    : See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#9.14.1
2023-02-05T15:34:59.684+01:00  INFO 49438 --- [    Test worker] o.f.c.internal.license.VersionPrinter    : 
2023-02-05T15:34:59.696+01:00  INFO 49438 --- [    Test worker] o.f.c.i.database.base.BaseDatabaseType   : Database: jdbc:postgresql://localhost:53361/somedatabasename (PostgreSQL 15.1)
2023-02-05T15:34:59.711+01:00  INFO 49438 --- [    Test worker] o.f.core.internal.command.DbValidate     : Successfully validated 1 migration (execution time 00:00.006s)
2023-02-05T15:34:59.719+01:00  INFO 49438 --- [    Test worker] o.f.c.i.s.JdbcTableSchemaHistory         : Creating Schema History table "public"."flyway_schema_history" ...
2023-02-05T15:34:59.756+01:00  INFO 49438 --- [    Test worker] o.f.core.internal.command.DbMigrate      : Current version of schema "public": << Empty Schema >>
2023-02-05T15:34:59.759+01:00  INFO 49438 --- [    Test worker] o.f.core.internal.command.DbMigrate      : Migrating schema "public" to version "1 -  init"
2023-02-05T15:34:59.772+01:00  INFO 49438 --- [    Test worker] o.f.core.internal.command.DbMigrate      : Successfully applied 1 migration to schema "public", now at version v1 (execution time 00:00.019s)
2023-02-05T15:34:59.784+01:00  INFO 49438 --- [    Test worker] c.f.k.c.SignUpCustomerShould             : Starting SignUpCustomerShould using Java 17.0.4 with PID 49438 (started by fabri in /Users/fabri/personal/kotlin-orms)
2023-02-05T15:34:59.784+01:00  INFO 49438 --- [    Test worker] c.f.k.c.SignUpCustomerShould             : The following 1 profile is active: "dev"
2023-02-05T15:35:00.286+01:00  INFO 49438 --- [    Test worker] com.zaxxer.hikari.HikariDataSource       : HikariPool-2 - Starting...
2023-02-05T15:35:00.317+01:00  INFO 49438 --- [    Test worker] com.zaxxer.hikari.pool.HikariPool        : HikariPool-2 - Added connection org.postgresql.jdbc.PgConnection@95f1422
2023-02-05T15:35:00.317+01:00  INFO 49438 --- [    Test worker] com.zaxxer.hikari.HikariDataSource       : HikariPool-2 - Start completed.
2023-02-05T15:35:00.318+01:00  INFO 49438 --- [    Test worker] o.f.c.i.database.base.BaseDatabaseType   : Database: jdbc:postgresql://localhost:53361/somedatabasename (PostgreSQL 15.1)
2023-02-05T15:35:00.329+01:00  INFO 49438 --- [    Test worker] o.f.core.internal.command.DbValidate     : Successfully validated 1 migration (execution time 00:00.005s)
2023-02-05T15:35:00.356+01:00  INFO 49438 --- [    Test worker] o.f.core.internal.command.DbMigrate      : Current version of schema "public": 1
2023-02-05T15:35:00.357+01:00  INFO 49438 --- [    Test worker] o.f.core.internal.command.DbMigrate      : Schema "public" is up to date. No migration necessary.
2023-02-05T15:35:00.544+01:00  INFO 49438 --- [    Test worker] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port 53385
2023-02-05T15:35:00.550+01:00  INFO 49438 --- [    Test worker] c.f.k.c.SignUpCustomerShould             : Started SignUpCustomerShould in 72.575 seconds (process running for 76.224)
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
